// <auto-generated />
namespace HotelAPI.Net_Framework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HotelBDD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HotelBDD));
        
        string IMigrationMetadata.Id
        {
            get { return "202104200032258_HotelBDD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
